framework:
    default_locale: en
    enabled_locales: ['en', 'es', 'it']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
